ssh -i "mydockerhostkeypair25aug.pem" ubuntu@ec2-18-119-0-149.us-east-2.compute.amazonaws.com

sudo -i
apt-get update


1. download the script
#
#   $ curl -fsSL https://get.docker.com -o install-docker.sh
#
# 2. verify the script's content
#
#   $ cat install-docker.sh
#
# 3. run the script with --dry-run to verify the steps it executes
#
#   $ sh install-docker.sh --dry-run
#
# 4. run the script either as root, or using sudo to perform the installation.
#
#   $ sudo sh install-docker.sh


docker --version

docker run --name myc1 -d -p 8081:80 nginx
docker run --name myc2 -d -p 8082:8080 jenkins:2.60.3 
docker run --name myc3 -d -p 



pip install "apache-airflow[postgres]==2.5.0" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.5.0/constraints-3.7.txt"

sed -i 's#sqlite:////home/ubuntu/airflow/airflow.db#postgresql+psycopg2://airflow:airflow@localhost/airflow#g' airflow.cfg

sed -i 's#SequentialExecutor#LocalExecutor#g' airflow.cfg






























sudo apt update
sudo apt install python3-pip
sudo apt install sqlite3
sudo apt install python3.10-venv
python3 -m venv venv
source venv/bin/activate
sudo apt-get install libpq-dev
pip install "apache-airflow[postgres]==2.5.0" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.5.0/constraints-3.7.txt"
airflow db init
sudo apt-get install postgresql postgresql-contrib
sudo -i -u postgres
psql
CREATE DATABASE airfloweg; 
CREATE USER airflowuser WITH PASSWORD 'airflow';
GRANT ALL PRIVILEGES ON DATABASES airfloweg TO airflowuser;

\q
logout
ls
cd airflow/
ls
sed -i 's#sqlite:////home/ubuntu/airflow/airflow.db#postgresql+psycopg2://airflow:airflow@localhost/airflow#g' airflow.cfg
grep sql_alchemy airflow.cfg
grep executor airflow.cfg
sed -i 's#SequentialExecutor#LocalExecutor#g' airflow.cfg
airflow db init
airflow users create -u airflow -f airflow -l airflow -r Admin -e airflow@gmail.com

password : airflow  confirm password : airflow

airflow webserver &

airflow scheduler

go to ec2 instance and select public IPV4 DNS :8080

username : airflow
password : airflow

DAG's Page







